services:
  mongo:
    image: mongo:5.0
    container_name: friendfinder_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: friendfinder_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/friendfinder
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: friendfinder_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: friendfinder_nginx
    ports:
      - "25580:25580"
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data:
  backend_node_modules:
  frontend_node_modules: