version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: friendfinder_mongo
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
