import express from "express";
import protect from "../middleware/authorizeuser";
import {accessChat, fetchChat,createGroup, renameGroups, addToGroup, removeFromGroup} from "../controllers/chat.controller";
const router = express.Router();
router.route('/').post(protect, accessChat);
router.route('/').get(protect, fetchChat);
router.route('/group').post(protect, createGroup);
router.route('/rename').put(protect, renameGroups);
router.route('/groupadd').put(protect, addToGroup);
router.route('/groupremove').put(protect, removeFromGroup);
export default router;